name: mandadito
description: App de despensa - control de caducidad y lista de compras
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Para el escaneo de código de barras
  mobile_scanner: ^5.2.3

  #Manejo de la base de datos local
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4

  #Maneja las notificaciones programadas
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

  #Se hace el consumo de API Open Food Facts para autocompletar producto
  http: ^1.2.2

  #Para el manejo de estados
  provider: ^6.1.2

  #Maneja las fechas
  intl: ^0.19.0

  #Maneja los permisos de cámara y notificaciones
  permission_handler: ^11.3.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
